In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = [15, 6]
%config InlineBackend.figure_format = 'retina'

import plotly.express as px
import plotly.graph_objects as go

/kaggle/input/police-deaths-in-usa-from-1791-to-2022/scrapper.py
/kaggle/input/police-deaths-in-usa-from-1791-to-2022/police_deaths_in_america.csv

# Dataset: Police Deaths in USA from 1791 to 2022
### Analyzed on June 9, 2022

The dataset contains 10 features of which 8 are of string type and 1 is Boolean while another being integer. This dataset contains the information about the police officers who have passed away while on duty. These are the data points collected and stored by the Officer Down Memorial Page Organization. Let us perform EDA & Time Series Forcasting on the dataset to understand the relationship between various features present in the dataset.

In [2]:
df = pd.read_csv('/kaggle/input/police-deaths-in-usa-from-1791-to-2022/police_deaths_in_america.csv')
df

,Rank,Name,Cause_of_Death,Date,Year,Month,Day,Department,State,K9_Unit
0,Constable,Darius Quimby,Stabbed,"Monday, January 3, 1791",1791,January,Monday,"Albany County Constable's Office, NY",New York,0
1,Sheriff,Cornelius Hogeboom,Gunfire,"Saturday, October 22, 1791",1791,October,Saturday,"Columbia County Sheriff's Office, NY",New York,0
2,Deputy Sheriff,Isaac Smith,Gunfire,"Thursday, May 17, 1792",1792,May,Thursday,"Westchester County Sheriff's Department, NY",New York,0
3,Marshal,Robert Forsyth,Gunfire,"Saturday, January 11, 1794",1794,January,Saturday,United States Department of Justice - United S...,United States,0
4,Deputy Sheriff,Robert Berwick,Gunfire,"Thursday, June 29, 1797",1797,June,Thursday,"New York County Sheriff's Office, NY",New York,0
...,...,...,...,...,...,...,...,...,...,...
26264,K9,Ciro,Fire,"Thursday, March 3, 2022",2022,March,Thursday,"Humphreys County Sheriff's Office, TN",Tennessee,1
26265,K9,Dash,Gunfire,"Wednesday, March 9, 2022",2022,March,Wednesday,"Shepherdsville Police Department, KY",Kentucky,1
26266,K9,Major,Gunfire,"Sunday, April 10, 2022",2022,April,Sunday,"Franklin County Sheriff's Office, NC",North Carolina,1
26267,K9,Jinx,Gunfire,"Monday, April 11, 2022",2022,April,Monday,"El Paso County Sheriff's Office, CO",Colorado,1
26268,K9,Mina,Animal related,"Monday, May 2, 2022",2022,May,Monday,United States Department of Homeland Security ...,United States,1

In [3]:
px.line(pd.DataFrame(df.groupby('Year').count().drop(['Name','Cause_of_Death','Date','State','Month','Day','Department','K9_Unit'],axis=1).rename(columns={'Rank':'Number of Deaths'})),title='Deaths')

On examining the above file, we see a presence of a boolean value. The k9 unit's deployment and mode of operation is different to that of human police force. Therefore both of the sets of data are to be processed differently.

# Human Police Force

In [4]:
k9_df = df[df['K9_Unit'] == 1].reset_index(drop=True)
df = df[df['K9_Unit'] == 0].reset_index(drop=True)
df.drop('K9_Unit',axis=1,inplace=True)
k9_df.drop('K9_Unit',axis=1,inplace=True) # Since the split is done based on the K9_Unit column, it is no longer required for further analysis.
k9_df

,Rank,Name,Cause_of_Death,Date,Year,Month,Day,Department,State
0,K9,Vag,Struck by streetcar,"Thursday, April 12, 1877",1877,April,Thursday,"Buffalo Police Department, NY",New York
1,K9,Danger,Struck by train,"Tuesday, June 9, 1896",1896,June,Tuesday,"New York, Chicago and St. Louis Railroad Polic...",United States
2,K9,Ollie,Struck by vehicle,"Thursday, August 26, 1909",1909,August,Thursday,"New York City Police Department, NY",New York
3,K9,Trooper,Assault,"Friday, March 17, 1961",1961,March,Friday,"Kansas City Police Department, MO",Missouri
4,K9,Baron,Assault,"Wednesday, September 12, 1962",1962,September,Wednesday,"Virginia State Police, VA",Virginia
...,...,...,...,...,...,...,...,...,...
478,K9,Ciro,Fire,"Thursday, March 3, 2022",2022,March,Thursday,"Humphreys County Sheriff's Office, TN",Tennessee
479,K9,Dash,Gunfire,"Wednesday, March 9, 2022",2022,March,Wednesday,"Shepherdsville Police Department, KY",Kentucky
480,K9,Major,Gunfire,"Sunday, April 10, 2022",2022,April,Sunday,"Franklin County Sheriff's Office, NC",North Carolina
481,K9,Jinx,Gunfire,"Monday, April 11, 2022",2022,April,Monday,"El Paso County Sheriff's Office, CO",Colorado
482,K9,Mina,Animal related,"Monday, May 2, 2022",2022,May,Monday,United States Department of Homeland Security ...,United States

In [5]:
df

,Rank,Name,Cause_of_Death,Date,Year,Month,Day,Department,State
0,Constable,Darius Quimby,Stabbed,"Monday, January 3, 1791",1791,January,Monday,"Albany County Constable's Office, NY",New York
1,Sheriff,Cornelius Hogeboom,Gunfire,"Saturday, October 22, 1791",1791,October,Saturday,"Columbia County Sheriff's Office, NY",New York
2,Deputy Sheriff,Isaac Smith,Gunfire,"Thursday, May 17, 1792",1792,May,Thursday,"Westchester County Sheriff's Department, NY",New York
3,Marshal,Robert Forsyth,Gunfire,"Saturday, January 11, 1794",1794,January,Saturday,United States Department of Justice - United S...,United States
4,Deputy Sheriff,Robert Berwick,Gunfire,"Thursday, June 29, 1797",1797,June,Thursday,"New York County Sheriff's Office, NY",New York
...,...,...,...,...,...,...,...,...,...
25781,Supervisory Police Officer,"Yiu Tak ""Louis"" Tao",9/11 related illness,"Tuesday, May 17, 2022",2022,May,Tuesday,United States Department of Justice - Federal ...,United States
25782,Senior Correctional Police Officer,Daniel Sincavage,Automobile crash,"Thursday, May 19, 2022",2022,May,Thursday,"New Jersey Department of Corrections, NJ",New Jersey
25783,Officer Trainee,Cody Alan Olafson,Duty related illness,"Friday, May 20, 2022",2022,May,Friday,United States Department of Homeland Security ...,United States
25784,Police Officer,Houston Tipping,Training accident,"Sunday, May 29, 2022",2022,May,Sunday,"Los Angeles Police Department, CA",California
25785,Officer,Adrian Lopez,Gunfire,"Friday, June 3, 2022",2022,June,Friday,White Mountain Apache Tribal Police Department...,United States

#### There are 25786 instances of police officers falling down in Non-K9 units while there are 483 instances of officers in K9 units that have fallen down.

## Non K9 Officer data analysis

### State-wise analysis

In [6]:
df_state = df.groupby('State').count().drop(['Name','Cause_of_Death','Date','Year','Month','Day','Department'],axis=1)
df_state = df_state.rename(columns={'Rank':'Deaths'}).sort_values(by='Deaths',ascending=False)
df_state.head(10)

               Deaths
State
Texas            2203
United States    1951
New York         1868
California       1730
Illinois         1158
Pennsylvania     1086
Kentucky          938
Florida           924
Ohio              888
Georgia           836

In [7]:
df_state.drop('United States',axis=0,inplace=True) # We remove this category as we are interested to know the state department statistics rather than federal office statistics.
fig = px.bar(df_state,title='Officers fallen down by state')
fig.update_traces(textfont_size=12, textangle=45, textposition="outside",cliponaxis=False)
fig.show()

We can observe from the above plot that the **Texas**, **New York** and **California** have far more deaths than the next state ,**Illinois**. So let us analyze other statistics about these states in detail.

In [8]:
df_interested_states = df[df['State'].isin(['California','Texas','New York'])]
df_interested_states

,Rank,Name,Cause_of_Death,Date,Year,Month,Day,Department,State
0,Constable,Darius Quimby,Stabbed,"Monday, January 3, 1791",1791,January,Monday,"Albany County Constable's Office, NY",New York
1,Sheriff,Cornelius Hogeboom,Gunfire,"Saturday, October 22, 1791",1791,October,Saturday,"Columbia County Sheriff's Office, NY",New York
2,Deputy Sheriff,Isaac Smith,Gunfire,"Thursday, May 17, 1792",1792,May,Thursday,"Westchester County Sheriff's Department, NY",New York
4,Deputy Sheriff,Robert Berwick,Gunfire,"Thursday, June 29, 1797",1797,June,Thursday,"New York County Sheriff's Office, NY",New York
8,Watchman,Christian Luswanger,Stabbed,"Thursday, December 25, 1806",1806,December,Thursday,"New York City Night Watch, NY",New York
...,...,...,...,...,...,...,...,...,...
25758,Sergeant,Barbara Majors Fenley,Fire,"Thursday, March 17, 2022",2022,March,Thursday,"Eastland County Sheriff's Office, TX",Texas
25767,Deputy Sheriff,Darren Almendarez,Gunfire,"Thursday, March 31, 2022",2022,March,Thursday,"Harris County Sheriff's Office, TX",Texas
25770,Deputy Constable,Jennifer Lauren Chavis,Vehicular assault,"Saturday, April 2, 2022",2022,April,Saturday,"Harris County Constable's Office - Precinct 7, TX",Texas
25778,Deputy Sheriff,Robert Adam Howard,Automobile crash,"Wednesday, May 11, 2022",2022,May,Wednesday,"Harris County Sheriff's Office, TX",Texas
25784,Police Officer,Houston Tipping,Training accident,"Sunday, May 29, 2022",2022,May,Sunday,"Los Angeles Police Department, CA",California

In [9]:
df_interested_states = pd.DataFrame(df_interested_states.groupby(by=['Year','State'],as_index=False).count().drop(['Name','Cause_of_Death','Date','Month','Day','Department'],axis=1))
df_interested_states = df_interested_states.rename(columns={'Rank':'Deaths'})
df_interested_states

     Year       State  Deaths
0    1791    New York       2
1    1792    New York       1
2    1797    New York       1
3    1806    New York       1
4    1818    New York       1
..    ...         ...     ...
503  2021    New York      28
504  2021       Texas     107
505  2022  California       7
506  2022    New York       4
507  2022       Texas      24

[508 rows x 3 columns]

In [10]:
fig2 = px.line(df_interested_states,y='Deaths',x='Year',color='State',markers=True)
fig2.update_layout(hovermode="x unified")
fig2.show()

Based on the above graph, we can see that new york has the oldest records of the 3 states. The earlier records are absent as the states were not added to the constitution. Texas was added to the USA around the years of 1830 - 1845. California was added to the Constitution of USA in 1850. Prior to these years, the data is not present and even if present need not obey the same rules of recording the relevant statistics.

In [11]:
fig2 = px.line(df_interested_states[df_interested_states['Year'] > 1980],y='Deaths',x='Year',color='State',markers=True,title='Deaths from 1980')
fig2.update_layout(hovermode="x unified")
fig2.show()

In [12]:
df_ny = df[(df['State'] == 'New York') & (df['Year'] == 2001)].groupby('Cause_of_Death').count().drop(['Name','State','Date','Year','Month','Day','Department'],axis=1)
df_ny.rename(columns ={'Rank':'Count'})
df_ny

                  Rank
Cause_of_Death
Terrorist attack    69

In [13]:
df_tx_2021 = df[(df['State'] == 'Texas') & (df['Year'] == 2021)].groupby('Cause_of_Death').count().drop(['Name','State','Date','Year','Month','Day','Department'],axis=1)
df_tx_2021.rename(columns ={'Rank':'Count'})
df_tx_2021

                   Rank
Cause_of_Death
Automobile crash      1
COVID19              95
Gunfire               8
Heart attack          2
Vehicular assault     1

In [14]:
df_tx_2020 = df[(df['State'] == 'Texas') & (df['Year'] == 2020)].groupby('Cause_of_Death').count().drop(['Name','State','Date','Year','Month','Day','Department'],axis=1)
df_tx_2020.rename(columns ={'Rank':'Count'})
df_tx_2020

                       Rank
Cause_of_Death
Aircraft accident         1
Automobile crash          1
COVID19                  59
Gunfire                   7
Gunfire (Inadvertent)     1
Heart attack              2
Heatstroke                1
Struck by vehicle         2
Vehicular assault         2

On observing the data from recent past (~ 40 years), we see two spikes in deaths. One among them is the 9/11 attack and all the police deaths recorded in New York that year are from the terrorist attack. While the bigger peak in texas corresponds majority of the deaths occuring from Covid-19 pandemic.

### Day-wise analysis

In [15]:
px.bar(df.groupby('Day').count().drop(['Name','State','Date','Year','Month','Rank','Department'],axis=1).rename(columns={'Cause_of_Death':'Count'}),title='Deaths on various days')

From the above bar chart we can see that Saturday has the highest deaths while Wednesday has the least number of deaths.

### Cause of Death Analysis

In [16]:
px.bar(df.groupby('Cause_of_Death').count().drop(['Name','State','Date','Year','Month','Rank','Department'],axis=1).rename(columns={'Day':'Count'}),title='Deaths due to various reasons')

From the above graph, we can look at the cause of death. The cause that is the most popular is Gunfire. The second most popular is Automobile Crash. These reasons are so ubiqutous that no secondary analysis are required into the dataset for this feature.

### Rank wise Analysis

In [17]:
df_rank = df.groupby('Rank').count().drop(['Name','State','Date','Year','Month','Cause_of_Death','Department'],axis=1).rename(columns={'Day':'Count'})
px.bar(pd.DataFrame(df_rank[df_rank['Count']>100]),title='Deaths due to various reasons')

**Patrolman**, **Police Officer** and **Deputy Sheriff**s are the most dangerous positions/ranks in the police departments. Those in these positions need additional support force to better protect their lives. Some of the less important death rate among the ranks are ignored to show the important ones better in the graph.

## Forecasting

Developing some models to predict the number of police deaths for the next year. Using the algorith developed in [this](https://arxiv.org/abs/1905.10437) paper, we can perform univariate time series modeling. The features present in the dataset do not necessarily explain or cause the deaths of the police officers, therefore we cannot perform multi variate time series forecasting. We can perform feature engineering by combining data from other datasets and events that happened in the same time frame to create better models.

In [18]:
import tensorflow as tf
from tensorflow.keras.layers import Layer
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import layers
tf.__version__

'2.6.4'

In [19]:
# Creating NBeats block

class NBeatsBlock(Layer):
    def __init__(self,
               input_size: int,
               theta_size: int,
               horizon: int,
               n_neurons: int,
               n_layers: int,
               **kwargs):
        super().__init__(**kwargs)
        self.input_size = input_size
        self.theta_size = theta_size
        self.horizon = horizon
        self.n_neurons = n_neurons
        self.n_layers = n_layers
        
        # Block contains stack of 4 fully connected layers each has ReLU activation
        self.hidden = Sequential([])
        for _ in range(n_layers):
            self.hidden.add(Dense(n_neurons,activation='relu'))
        # Output of block is a theta layer with linear activation
        self.theta_layer = tf.keras.layers.Dense(theta_size, activation="linear", name="theta")
    
    def call(self,inputs):
        theta = self.theta_layer(self.hidden(inputs))
        
        backcast, forecast = theta[:,:self.input_size], theta[:,-self.horizon:]
        
        return backcast, forecast


dataset = pd.DataFrame(df.groupby('Year',as_index=False).count().drop(['Name','Cause_of_Death','Date','State','Month','Day','Department'],axis=1)).rename(columns={'Rank':'Count'})
dataset = dataset[dataset['Year'] > 1850]
dataset

     Year  Count
38   1851      9
39   1852      9
40   1853      9
41   1854     10
42   1855     15
..    ...    ...
205  2018    188
206  2019    158
207  2020    414
208  2021    622
209  2022    112

[172 rows x 2 columns]

In [20]:
from tensorflow.keras.utils import timeseries_dataset_from_array

HORIZON = 1
WINDOW_SIZE = 15

inputs = dataset['Count'][:-WINDOW_SIZE]
targets = dataset['Count'][WINDOW_SIZE:]

split_size = int(len(dataset) * 0.8)
X_train, y_train = inputs[:split_size], targets[:split_size]
X_test, y_test = inputs[split_size:], targets[split_size:]
len(X_train), len(y_train), len(X_test), len(y_test)

trainset = timeseries_dataset_from_array(X_train, y_train, sequence_length=WINDOW_SIZE,batch_size=1024).prefetch(tf.data.AUTOTUNE)
testset = timeseries_dataset_from_array(X_test, y_test, sequence_length=WINDOW_SIZE,batch_size=1024).prefetch(tf.data.AUTOTUNE)

trainset, testset

2022-06-11 03:31:22.384947: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-11 03:31:22.389425: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-11 03:31:22.390122: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-11 03:31:22.392075: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-06-11 03:31:22.392351: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-11 03:31:22.393050: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-11 03:31:22.393742: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-11 03:31:24.517198: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-11 03:31:24.518036: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-11 03:31:24.518678: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-11 03:31:24.519253: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 15385 MB memory:  -> device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0

(<PrefetchDataset shapes: ((None, None), (None,)), types: (tf.int64, tf.int64)>,
 <PrefetchDataset shapes: ((None, None), (None,)), types: (tf.int64, tf.int64)>)

In [21]:
N_EPOCHS = 500 # called "Iterations" in Table 18
N_NEURONS = 512 # called "Width" in Table 18
N_LAYERS = 4
N_STACKS = 30

INPUT_SIZE = WINDOW_SIZE * HORIZON # called "Lookback" in Table 18
THETA_SIZE = INPUT_SIZE + HORIZON

INPUT_SIZE, THETA_SIZE

(15, 16)

In [22]:
# 1. Setup N-BEATS Block layer
nbeats_block_layer = NBeatsBlock(input_size=INPUT_SIZE,
                                 theta_size=THETA_SIZE,
                                 horizon=HORIZON,
                                 n_neurons=N_NEURONS,
                                 n_layers=N_LAYERS,
                                 name="InitialBlock")

# 2. Create input to stacks
stack_input = layers.Input(shape=(INPUT_SIZE), name="stack_input")

# 3. Create initial backcast and forecast input (backwards predictions are referred to as residuals in the paper)
backcast, forecast = nbeats_block_layer(stack_input)
# Add in subtraction residual link, thank you to: https://github.com/mrdbourke/tensorflow-deep-learning/discussions/174 
residuals = layers.subtract([stack_input, backcast], name=f"subtract_00") 

# 4. Create stacks of blocks
for i, _ in enumerate(range(N_STACKS-1)): # first stack is already creted in (3)

  # 5. Use the NBeatsBlock to calculate the backcast as well as block forecast
  backcast, block_forecast = NBeatsBlock(
      input_size=INPUT_SIZE,
      theta_size=THETA_SIZE,
      horizon=HORIZON,
      n_neurons=N_NEURONS,
      n_layers=N_LAYERS,
      name=f"NBeatsBlock_{i}"
  )(residuals) # pass it in residuals (the backcast)

  # 6. Create the double residual stacking
  residuals = layers.subtract([residuals, backcast], name=f"subtract_{i}") 
  forecast = layers.add([forecast, block_forecast], name=f"add_{i}")

# 7. Put the stack model together
model_nbeats = tf.keras.Model(inputs=stack_input, 
                         outputs=forecast, 
                         name="model_7_N-BEATS")

# 8. Compile with MAE loss and Adam optimizer
model_nbeats.compile(loss="mae",
                optimizer=tf.keras.optimizers.Adam(0.001),
                metrics=["mae", "mse"])

# 9. Fit the model with EarlyStopping and ReduceLROnPlateau callbacks
model_nbeats.fit(trainset,
            epochs=N_EPOCHS,
            validation_data=testset,
            verbose=1,
            callbacks=[tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=200, restore_best_weights=True),
                      tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", patience=100, verbose=1)])

2022-06-11 03:31:26.592636: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)

Epoch 1/500
1/1 [==============================] - 9s 9s/step - loss: 132.1064 - mae: 132.1064 - mse: 22262.6680 - val_loss: 7315.0464 - val_mae: 7315.0464 - val_mse: 53527212.0000
Epoch 2/500
1/1 [==============================] - 0s 104ms/step - loss: 6056.0479 - mae: 6056.0479 - mse: 48805380.0000 - val_loss: 1168.1207 - val_mae: 1168.1207 - val_mse: 1368868.0000
Epoch 3/500
1/1 [==============================] - 0s 108ms/step - loss: 970.0338 - mae: 970.0338 - mse: 1310381.2500 - val_loss: 429.4260 - val_mae: 429.4260 - val_mse: 184555.0469
Epoch 4/500
1/1 [==============================] - 0s 105ms/step - loss: 350.0040 - mae: 350.0040 - mse: 177683.6406 - val_loss: 421.6145 - val_mae: 421.6145 - val_mse: 194644.3594
Epoch 5/500
1/1 [==============================] - 0s 105ms/step - loss: 395.1009 - mae: 395.1009 - mse: 217646.7656 - val_loss: 16.1685 - val_mae: 16.1685 - val_mse: 355.3372
Epoch 6/500
1/1 [==============================] - 0s 107ms/step - loss: 35.5499 - mae: 35.5499 - mse: 1978.3964 - val_loss: 36.1124 - val_mae: 36.1124 - val_mse: 1755.1953
Epoch 7/500
1/1 [==============================] - 0s 117ms/step - loss: 31.6085 - mae: 31.6085 - mse: 1788.9158 - val_loss: 807.7145 - val_mae: 807.7145 - val_mse: 671425.4375
Epoch 8/500
1/1 [==============================] - 0s 107ms/step - loss: 687.7339 - mae: 687.7339 - mse: 670755.6250 - val_loss: 96.8131 - val_mae: 96.8131 - val_mse: 10391.3203
Epoch 9/500
1/1 [==============================] - 0s 105ms/step - loss: 83.7848 - mae: 83.7848 - mse: 8979.7998 - val_loss: 78.4727 - val_mae: 78.4727 - val_mse: 6393.4785
Epoch 10/500
1/1 [==============================] - 0s 102ms/step - loss: 64.5472 - mae: 64.5472 - mse: 7883.6973 - val_loss: 66.6730 - val_mae: 66.6730 - val_mse: 4635.0645
Epoch 11/500
1/1 [==============================] - 0s 105ms/step - loss: 53.1342 - mae: 53.1342 - mse: 6018.6768 - val_loss: 11.7399 - val_mae: 11.7399 - val_mse: 289.3073
Epoch 12/500
1/1 [==============================] - 0s 104ms/step - loss: 34.9844 - mae: 34.9844 - mse: 2130.3574 - val_loss: 31.4471 - val_mae: 31.4471 - val_mse: 1407.1914
Epoch 13/500
1/1 [==============================] - 0s 147ms/step - loss: 38.5128 - mae: 38.5128 - mse: 2320.7026 - val_loss: 26.1293 - val_mae: 26.1293 - val_mse: 766.1115
Epoch 14/500
1/1 [==============================] - 0s 188ms/step - loss: 24.4152 - mae: 24.4152 - mse: 1157.2977 - val_loss: 34.2448 - val_mae: 34.2448 - val_mse: 1392.7614
Epoch 15/500
1/1 [==============================] - 0s 148ms/step - loss: 29.5327 - mae: 29.5327 - mse: 1652.7500 - val_loss: 16.7650 - val_mae: 16.7650 - val_mse: 703.2230
Epoch 16/500
1/1 [==============================] - 0s 109ms/step - loss: 19.4956 - mae: 19.4956 - mse: 591.0921 - val_loss: 22.3736 - val_mae: 22.3736 - val_mse: 1020.7720
Epoch 17/500
1/1 [==============================] - 0s 107ms/step - loss: 20.3933 - mae: 20.3933 - mse: 654.2590 - val_loss: 22.4061 - val_mae: 22.4061 - val_mse: 698.1652
Epoch 18/500
1/1 [==============================] - 0s 104ms/step - loss: 16.3249 - mae: 16.3249 - mse: 520.6385 - val_loss: 21.7688 - val_mae: 21.7688 - val_mse: 754.6114
Epoch 19/500
1/1 [==============================] - 0s 103ms/step - loss: 14.0646 - mae: 14.0646 - mse: 372.1997 - val_loss: 27.4134 - val_mae: 27.4134 - val_mse: 1402.0264
Epoch 20/500
1/1 [==============================] - 0s 103ms/step - loss: 18.2764 - mae: 18.2764 - mse: 549.3233 - val_loss: 23.6445 - val_mae: 23.6445 - val_mse: 843.4230
Epoch 21/500
1/1 [==============================] - 0s 106ms/step - loss: 13.7938 - mae: 13.7938 - mse: 359.3416 - val_loss: 21.0621 - val_mae: 21.0621 - val_mse: 754.9771
Epoch 22/500
1/1 [==============================] - 0s 104ms/step - loss: 11.6952 - mae: 11.6952 - mse: 260.6130 - val_loss: 20.1247 - val_mae: 20.1247 - val_mse: 772.5600
Epoch 23/500
1/1 [==============================] - 0s 102ms/step - loss: 12.5823 - mae: 12.5823 - mse: 267.8321 - val_loss: 21.6819 - val_mae: 21.6819 - val_mse: 763.3160
Epoch 24/500
1/1 [==============================] - 0s 103ms/step - loss: 10.9870 - mae: 10.9870 - mse: 238.1395 - val_loss: 21.2187 - val_mae: 21.2187 - val_mse: 707.0166
Epoch 25/500
1/1 [==============================] - 0s 103ms/step - loss: 9.8366 - mae: 9.8366 - mse: 184.4813 - val_loss: 22.3813 - val_mae: 22.3813 - val_mse: 765.6988
Epoch 26/500
1/1 [==============================] - 0s 105ms/step - loss: 8.6360 - mae: 8.6360 - mse: 160.3332 - val_loss: 22.3172 - val_mae: 22.3172 - val_mse: 786.5482
Epoch 27/500
1/1 [==============================] - 0s 106ms/step - loss: 8.3412 - mae: 8.3412 - mse: 140.5540 - val_loss: 25.9208 - val_mae: 25.9208 - val_mse: 976.0821
Epoch 28/500
1/1 [==============================] - 0s 102ms/step - loss: 12.5563 - mae: 12.5563 - mse: 245.8858 - val_loss: 24.4333 - val_mae: 24.4333 - val_mse: 1017.0384
Epoch 29/500
1/1 [==============================] - 0s 105ms/step - loss: 15.6425 - mae: 15.6425 - mse: 352.9182 - val_loss: 22.5167 - val_mae: 22.5167 - val_mse: 771.3745
Epoch 30/500
1/1 [==============================] - 0s 108ms/step - loss: 6.9463 - mae: 6.9463 - mse: 100.2269 - val_loss: 19.7572 - val_mae: 19.7572 - val_mse: 674.6213
Epoch 31/500
1/1 [==============================] - 0s 121ms/step - loss: 6.6096 - mae: 6.6096 - mse: 93.8208 - val_loss: 28.0443 - val_mae: 28.0443 - val_mse: 1008.3699
Epoch 32/500
1/1 [==============================] - 0s 108ms/step - loss: 14.5602 - mae: 14.5602 - mse: 314.3236 - val_loss: 18.6391 - val_mae: 18.6391 - val_mse: 632.0737
Epoch 33/500
1/1 [==============================] - 0s 103ms/step - loss: 7.5125 - mae: 7.5125 - mse: 106.8157 - val_loss: 21.2972 - val_mae: 21.2972 - val_mse: 671.8103
Epoch 34/500
1/1 [==============================] - 0s 110ms/step - loss: 6.2431 - mae: 6.2431 - mse: 80.4687 - val_loss: 19.4480 - val_mae: 19.4480 - val_mse: 659.6117
Epoch 35/500
1/1 [==============================] - 0s 106ms/step - loss: 5.4737 - mae: 5.4737 - mse: 69.3729 - val_loss: 25.5594 - val_mae: 25.5594 - val_mse: 884.6236
Epoch 36/500
1/1 [==============================] - 0s 104ms/step - loss: 10.7646 - mae: 10.7646 - mse: 180.6841 - val_loss: 20.5328 - val_mae: 20.5328 - val_mse: 802.4399
Epoch 37/500
1/1 [==============================] - 0s 112ms/step - loss: 10.7383 - mae: 10.7383 - mse: 193.3156 - val_loss: 21.8828 - val_mae: 21.8828 - val_mse: 728.7005
Epoch 38/500
1/1 [==============================] - 0s 105ms/step - loss: 6.4776 - mae: 6.4776 - mse: 80.4600 - val_loss: 22.5793 - val_mae: 22.5793 - val_mse: 721.6172
Epoch 39/500
1/1 [==============================] - 0s 109ms/step - loss: 6.0016 - mae: 6.0016 - mse: 60.6246 - val_loss: 22.2226 - val_mae: 22.2226 - val_mse: 831.2202
Epoch 40/500
1/1 [==============================] - 0s 105ms/step - loss: 16.3501 - mae: 16.3501 - mse: 394.6334 - val_loss: 18.6085 - val_mae: 18.6085 - val_mse: 555.8577
Epoch 41/500
1/1 [==============================] - 0s 106ms/step - loss: 7.3632 - mae: 7.3632 - mse: 103.1089 - val_loss: 29.2115 - val_mae: 29.2115 - val_mse: 1093.3970
Epoch 42/500
1/1 [==============================] - 0s 104ms/step - loss: 15.7971 - mae: 15.7971 - mse: 354.3661 - val_loss: 22.3578 - val_mae: 22.3578 - val_mse: 629.5860
Epoch 43/500
1/1 [==============================] - 0s 105ms/step - loss: 7.1838 - mae: 7.1838 - mse: 115.2577 - val_loss: 21.0189 - val_mae: 21.0189 - val_mse: 836.4385
Epoch 44/500
1/1 [==============================] - 0s 108ms/step - loss: 19.5922 - mae: 19.5922 - mse: 552.2028 - val_loss: 18.4287 - val_mae: 18.4287 - val_mse: 758.5842
Epoch 45/500
1/1 [==============================] - 0s 105ms/step - loss: 16.4682 - mae: 16.4682 - mse: 398.2124 - val_loss: 26.7913 - val_mae: 26.7913 - val_mse: 922.4371
Epoch 46/500
1/1 [==============================] - 0s 105ms/step - loss: 9.1525 - mae: 9.1525 - mse: 146.0693 - val_loss: 30.6522 - val_mae: 30.6522 - val_mse: 1174.9301
Epoch 47/500
1/1 [==============================] - 0s 102ms/step - loss: 12.1300 - mae: 12.1300 - mse: 219.6018 - val_loss: 21.1258 - val_mae: 21.1258 - val_mse: 741.5881
Epoch 48/500
1/1 [==============================] - 0s 105ms/step - loss: 6.8872 - mae: 6.8872 - mse: 87.6870 - val_loss: 20.6399 - val_mae: 20.6399 - val_mse: 699.6301
Epoch 49/500
1/1 [==============================] - 0s 105ms/step - loss: 7.3187 - mae: 7.3187 - mse: 99.4913 - val_loss: 27.1691 - val_mae: 27.1691 - val_mse: 1043.8043
Epoch 50/500
1/1 [==============================] - 0s 110ms/step - loss: 10.2845 - mae: 10.2845 - mse: 165.4910 - val_loss: 24.6152 - val_mae: 24.6152 - val_mse: 828.9681
Epoch 51/500
1/1 [==============================] - 0s 109ms/step - loss: 6.7564 - mae: 6.7564 - mse: 78.6665 - val_loss: 19.3342 - val_mae: 19.3342 - val_mse: 606.6733
Epoch 52/500
1/1 [==============================] - 0s 106ms/step - loss: 10.9548 - mae: 10.9548 - mse: 170.1093 - val_loss: 19.9369 - val_mae: 19.9369 - val_mse: 601.5954
Epoch 53/500
1/1 [==============================] - 0s 106ms/step - loss: 7.4640 - mae: 7.4640 - mse: 86.1530 - val_loss: 29.5621 - val_mae: 29.5621 - val_mse: 1195.8379
Epoch 54/500
1/1 [==============================] - 0s 137ms/step - loss: 13.2115 - mae: 13.2115 - mse: 277.7643 - val_loss: 27.0903 - val_mae: 27.0903 - val_mse: 997.4022
Epoch 55/500
1/1 [==============================] - 0s 109ms/step - loss: 9.3337 - mae: 9.3337 - mse: 150.0286 - val_loss: 20.3964 - val_mae: 20.3964 - val_mse: 668.6833
Epoch 56/500
1/1 [==============================] - 0s 118ms/step - loss: 11.1779 - mae: 11.1779 - mse: 177.0811 - val_loss: 19.7204 - val_mae: 19.7204 - val_mse: 617.3367
Epoch 57/500
1/1 [==============================] - 0s 115ms/step - loss: 9.9508 - mae: 9.9508 - mse: 154.7076 - val_loss: 26.0300 - val_mae: 26.0300 - val_mse: 995.6558
Epoch 58/500
1/1 [==============================] - 0s 114ms/step - loss: 11.2405 - mae: 11.2405 - mse: 226.0539 - val_loss: 27.3184 - val_mae: 27.3184 - val_mse: 1069.3531
Epoch 59/500
1/1 [==============================] - 0s 113ms/step - loss: 12.3277 - mae: 12.3277 - mse: 268.7776 - val_loss: 20.2607 - val_mae: 20.2607 - val_mse: 560.3512
Epoch 60/500
1/1 [==============================] - 0s 111ms/step - loss: 5.0214 - mae: 5.0214 - mse: 46.5854 - val_loss: 18.4886 - val_mae: 18.4886 - val_mse: 624.6281
Epoch 61/500
1/1 [==============================] - 0s 108ms/step - loss: 9.6061 - mae: 9.6061 - mse: 127.6697 - val_loss: 23.4619 - val_mae: 23.4619 - val_mse: 696.4665
Epoch 62/500
1/1 [==============================] - 0s 114ms/step - loss: 5.2036 - mae: 5.2036 - mse: 60.2272 - val_loss: 28.0266 - val_mae: 28.0266 - val_mse: 958.0261
Epoch 63/500
1/1 [==============================] - 0s 110ms/step - loss: 10.5264 - mae: 10.5264 - mse: 201.2002 - val_loss: 22.1822 - val_mae: 22.1822 - val_mse: 652.2015
Epoch 64/500
1/1 [==============================] - 0s 104ms/step - loss: 4.3416 - mae: 4.3416 - mse: 36.2082 - val_loss: 18.7976 - val_mae: 18.7976 - val_mse: 578.6457
Epoch 65/500
1/1 [==============================] - 0s 113ms/step - loss: 5.8820 - mae: 5.8820 - mse: 51.7506 - val_loss: 24.3113 - val_mae: 24.3113 - val_mse: 832.3729
Epoch 66/500
1/1 [==============================] - 0s 108ms/step - loss: 8.1242 - mae: 8.1242 - mse: 97.9482 - val_loss: 22.4106 - val_mae: 22.4106 - val_mse: 694.7222
Epoch 67/500
1/1 [==============================] - 0s 105ms/step - loss: 4.9522 - mae: 4.9522 - mse: 42.4421 - val_loss: 20.2130 - val_mae: 20.2130 - val_mse: 616.6656
Epoch 68/500
1/1 [==============================] - 0s 112ms/step - loss: 9.2027 - mae: 9.2027 - mse: 123.7597 - val_loss: 21.5679 - val_mae: 21.5679 - val_mse: 662.8860
Epoch 69/500
1/1 [==============================] - 0s 110ms/step - loss: 3.6204 - mae: 3.6204 - mse: 24.3989 - val_loss: 29.2466 - val_mae: 29.2466 - val_mse: 1186.4093
Epoch 70/500
1/1 [==============================] - 0s 110ms/step - loss: 12.1883 - mae: 12.1883 - mse: 200.9478 - val_loss: 26.0608 - val_mae: 26.0608 - val_mse: 915.9020
Epoch 71/500
1/1 [==============================] - 0s 109ms/step - loss: 7.6918 - mae: 7.6918 - mse: 102.7882 - val_loss: 20.0029 - val_mae: 20.0029 - val_mse: 684.3584
Epoch 72/500
1/1 [==============================] - 0s 107ms/step - loss: 12.6296 - mae: 12.6296 - mse: 236.5952 - val_loss: 20.0820 - val_mae: 20.0820 - val_mse: 753.2891
Epoch 73/500
1/1 [==============================] - 0s 107ms/step - loss: 14.5712 - mae: 14.5712 - mse: 307.9475 - val_loss: 22.6664 - val_mae: 22.6664 - val_mse: 646.3317
Epoch 74/500
1/1 [==============================] - 0s 109ms/step - loss: 5.3354 - mae: 5.3354 - mse: 50.5262 - val_loss: 31.5388 - val_mae: 31.5388 - val_mse: 1185.1354
Epoch 75/500
1/1 [==============================] - 0s 111ms/step - loss: 14.3992 - mae: 14.3992 - mse: 310.7708 - val_loss: 28.5196 - val_mae: 28.5196 - val_mse: 977.9504
Epoch 76/500
1/1 [==============================] - 0s 105ms/step - loss: 11.1675 - mae: 11.1675 - mse: 206.2343 - val_loss: 17.4351 - val_mae: 17.4351 - val_mse: 519.6363
Epoch 77/500
1/1 [==============================] - 0s 109ms/step - loss: 8.7487 - mae: 8.7487 - mse: 158.7208 - val_loss: 17.5858 - val_mae: 17.5858 - val_mse: 564.7612
Epoch 78/500
1/1 [==============================] - 0s 111ms/step - loss: 12.1938 - mae: 12.1938 - mse: 231.6554 - val_loss: 19.9581 - val_mae: 19.9581 - val_mse: 547.5812
Epoch 79/500
1/1 [==============================] - 0s 108ms/step - loss: 2.9393 - mae: 2.9393 - mse: 18.1376 - val_loss: 25.7702 - val_mae: 25.7702 - val_mse: 958.7665
Epoch 80/500
1/1 [==============================] - 0s 105ms/step - loss: 10.2739 - mae: 10.2739 - mse: 170.6117 - val_loss: 23.4925 - val_mae: 23.4925 - val_mse: 742.4964
Epoch 81/500
1/1 [==============================] - 0s 112ms/step - loss: 5.6164 - mae: 5.6164 - mse: 85.8918 - val_loss: 20.7762 - val_mae: 20.7762 - val_mse: 729.1921
Epoch 82/500
1/1 [==============================] - 0s 103ms/step - loss: 9.9499 - mae: 9.9499 - mse: 160.4280 - val_loss: 23.5774 - val_mae: 23.5774 - val_mse: 778.0095
Epoch 83/500
1/1 [==============================] - 0s 103ms/step - loss: 5.6779 - mae: 5.6779 - mse: 59.8791 - val_loss: 31.3813 - val_mae: 31.3813 - val_mse: 1231.6790
Epoch 84/500
1/1 [==============================] - 0s 105ms/step - loss: 9.6697 - mae: 9.6697 - mse: 144.7063 - val_loss: 29.4123 - val_mae: 29.4123 - val_mse: 1102.2946
Epoch 85/500
1/1 [==============================] - 0s 128ms/step - loss: 8.2420 - mae: 8.2420 - mse: 117.3599 - val_loss: 21.3248 - val_mae: 21.3248 - val_mse: 618.3887
Epoch 86/500
1/1 [==============================] - 0s 110ms/step - loss: 7.5143 - mae: 7.5143 - mse: 111.7922 - val_loss: 20.3292 - val_mae: 20.3292 - val_mse: 586.0031
Epoch 87/500
1/1 [==============================] - 0s 104ms/step - loss: 7.7622 - mae: 7.7622 - mse: 108.3394 - val_loss: 26.2706 - val_mae: 26.2706 - val_mse: 851.6463
Epoch 88/500
1/1 [==============================] - 0s 182ms/step - loss: 5.8265 - mae: 5.8265 - mse: 55.0134 - val_loss: 25.6489 - val_mae: 25.6489 - val_mse: 821.4875
Epoch 89/500
1/1 [==============================] - 0s 176ms/step - loss: 5.6003 - mae: 5.6003 - mse: 48.6580 - val_loss: 19.3287 - val_mae: 19.3287 - val_mse: 618.4858
Epoch 90/500
1/1 [==============================] - 0s 161ms/step - loss: 7.4682 - mae: 7.4682 - mse: 90.7930 - val_loss: 20.1274 - val_mae: 20.1274 - val_mse: 573.6102
Epoch 91/500
1/1 [==============================] - 0s 100ms/step - loss: 4.7628 - mae: 4.7628 - mse: 40.1336 - val_loss: 25.1380 - val_mae: 25.1380 - val_mse: 850.0554
Epoch 92/500
1/1 [==============================] - 0s 104ms/step - loss: 9.4378 - mae: 9.4378 - mse: 125.4277 - val_loss: 22.9406 - val_mae: 22.9406 - val_mse: 639.8502
Epoch 93/500
1/1 [==============================] - 0s 100ms/step - loss: 4.8664 - mae: 4.8664 - mse: 45.7574 - val_loss: 17.6192 - val_mae: 17.6192 - val_mse: 478.4270
Epoch 94/500
1/1 [==============================] - 0s 101ms/step - loss: 11.4427 - mae: 11.4427 - mse: 178.8576 - val_loss: 17.7121 - val_mae: 17.7121 - val_mse: 492.4661
Epoch 95/500
1/1 [==============================] - 0s 101ms/step - loss: 11.6859 - mae: 11.6859 - mse: 190.1922 - val_loss: 22.8137 - val_mae: 22.8137 - val_mse: 628.0347
Epoch 96/500
1/1 [==============================] - 0s 102ms/step - loss: 4.3814 - mae: 4.3814 - mse: 35.9187 - val_loss: 27.3773 - val_mae: 27.3773 - val_mse: 1001.0122
Epoch 97/500
1/1 [==============================] - 0s 105ms/step - loss: 9.1041 - mae: 9.1041 - mse: 122.8577 - val_loss: 24.3133 - val_mae: 24.3133 - val_mse: 752.7048
Epoch 98/500
1/1 [==============================] - 0s 100ms/step - loss: 3.5200 - mae: 3.5200 - mse: 22.6488 - val_loss: 19.0236 - val_mae: 19.0236 - val_mse: 678.9164
Epoch 99/500
1/1 [==============================] - 0s 104ms/step - loss: 10.8831 - mae: 10.8831 - mse: 161.4149 - val_loss: 19.2404 - val_mae: 19.2404 - val_mse: 681.2640
Epoch 100/500
1/1 [==============================] - 0s 102ms/step - loss: 9.3733 - mae: 9.3733 - mse: 128.2915 - val_loss: 26.2596 - val_mae: 26.2596 - val_mse: 855.3284
Epoch 101/500
1/1 [==============================] - 0s 99ms/step - loss: 5.5579 - mae: 5.5579 - mse: 55.1125 - val_loss: 27.0066 - val_mae: 27.0066 - val_mse: 901.8469
Epoch 102/500
1/1 [==============================] - 0s 103ms/step - loss: 6.5596 - mae: 6.5596 - mse: 69.8643 - val_loss: 21.1946 - val_mae: 21.1946 - val_mse: 642.4670
Epoch 103/500
1/1 [==============================] - 0s 100ms/step - loss: 6.1158 - mae: 6.1158 - mse: 57.5722 - val_loss: 21.8343 - val_mae: 21.8343 - val_mse: 643.5997
Epoch 104/500
1/1 [==============================] - 0s 100ms/step - loss: 5.1112 - mae: 5.1112 - mse: 40.0573 - val_loss: 27.9132 - val_mae: 27.9132 - val_mse: 960.2344
Epoch 105/500
1/1 [==============================] - 0s 101ms/step - loss: 7.2172 - mae: 7.2172 - mse: 79.1119 - val_loss: 27.0565 - val_mae: 27.0565 - val_mse: 885.8694
Epoch 106/500
1/1 [==============================] - 0s 99ms/step - loss: 5.7197 - mae: 5.7197 - mse: 57.8001 - val_loss: 20.8337 - val_mae: 20.8337 - val_mse: 575.0546
Epoch 107/500
1/1 [==============================] - 0s 102ms/step - loss: 6.4928 - mae: 6.4928 - mse: 63.9074 - val_loss: 20.6814 - val_mae: 20.6814 - val_mse: 555.6557
Epoch 108/500
1/1 [==============================] - 0s 102ms/step - loss: 6.0346 - mae: 6.0346 - mse: 58.3382 - val_loss: 25.0445 - val_mae: 25.0445 - val_mse: 776.9664
Epoch 109/500
1/1 [==============================] - 0s 102ms/step - loss: 4.6108 - mae: 4.6108 - mse: 40.9517 - val_loss: 24.6167 - val_mae: 24.6167 - val_mse: 753.2095
Epoch 110/500
1/1 [==============================] - 0s 99ms/step - loss: 4.0383 - mae: 4.0383 - mse: 29.0852 - val_loss: 19.4726 - val_mae: 19.4726 - val_mse: 528.0687
Epoch 111/500
1/1 [==============================] - 0s 100ms/step - loss: 6.2412 - mae: 6.2412 - mse: 55.4453 - val_loss: 20.4304 - val_mae: 20.4304 - val_mse: 540.2207

Epoch 00111: ReduceLROnPlateau reducing learning rate to 0.00010000000474974513.
Epoch 112/500
1/1 [==============================] - 0s 100ms/step - loss: 3.8710 - mae: 3.8710 - mse: 26.8906 - val_loss: 20.9142 - val_mae: 20.9142 - val_mse: 552.7483
Epoch 113/500
1/1 [==============================] - 0s 103ms/step - loss: 3.1464 - mae: 3.1464 - mse: 18.3785 - val_loss: 21.6732 - val_mae: 21.6732 - val_mse: 580.7473
Epoch 114/500
1/1 [==============================] - 0s 101ms/step - loss: 2.3470 - mae: 2.3470 - mse: 10.4617 - val_loss: 22.4642 - val_mae: 22.4642 - val_mse: 620.7368
Epoch 115/500
1/1 [==============================] - 0s 102ms/step - loss: 2.2882 - mae: 2.2882 - mse: 8.8984 - val_loss: 23.0043 - val_mae: 23.0043 - val_mse: 654.4064
Epoch 116/500
1/1 [==============================] - 0s 102ms/step - loss: 2.6004 - mae: 2.6004 - mse: 11.3660 - val_loss: 23.1445 - val_mae: 23.1445 - val_mse: 663.8053
Epoch 117/500

In [23]:
model_nbeats.evaluate(testset)

1/1 [==============================] - 0s 69ms/step - loss: 11.7399 - mae: 11.7399 - mse: 289.3073

[11.73986530303955, 11.73986530303955, 289.3072509765625]

In [24]:
model_nbeats.predict(tf.expand_dims(dataset['Count'][-WINDOW_SIZE:],axis=0))

array([[140.4808]], dtype=float32)

Provided that there is no strong policy change and change in behaviour of the people over 2023, it is expected that there would be **140 police officers** will be sacrifying their lives in the year 2023 with most of them being Patrolman, Police Officer and Deputy Sheriffs.

## K9 Analysis

In [25]:
px.bar(k9_df.groupby('Cause_of_Death').count().drop(['Name','Date','Year','Month','Day','Department','State'],axis=1).rename(columns={'Rank':'Count'}).sort_values(by='Count',ascending=False))

In [26]:
px.bar(k9_df.groupby('State').count().drop(['Name','Date','Year','Month','Day','Department','Cause_of_Death'],axis=1).rename(columns={'Rank':'Count'}).sort_values(by='Count',ascending=False))

In [27]:
k9_list = []
iter_year = 1950
rows = pd.DataFrame(k9_df[k9_df['Year'] > 1961].groupby('Year',as_index=False).count()).drop(['Rank','Name','Date','Month','Day','Department','State'],axis=1).rename(columns={'Cause_of_Death':'Count'}).values.tolist()
i = 0
while True:
    if rows[i][0] == iter_year:
        k9_list.append(rows[i][1])
        i = i + 1
    else:
        k9_list.append(0)
    iter_year = iter_year + 1
    if iter_year > max([i[0] for i in rows]):
        break
k9_list

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 3,
 0,
 4,
 4,
 3,
 2,
 3,
 6,
 2,
 3,
 4,
 2,
 5,
 5,
 6,
 7,
 5,
 3,
 3,
 3,
 0,
 4,
 4,
 4,
 6,
 6,
 7,
 8,
 9,
 6,
 10,
 7,
 6,
 9,
 3,
 9,
 10,
 14,
 7,
 14,
 18,
 22,
 20,
 27,
 36,
 24,
 28,
 28,
 22,
 21,
 9]

In [28]:
HORIZON = 1
WINDOW_SIZE = 7

inputs = k9_list[:-WINDOW_SIZE]
targets = k9_list[WINDOW_SIZE:]

split_size = int(len(k9_list) * 0.8)
X_train, y_train = inputs[:split_size], targets[:split_size]
X_test, y_test = inputs[split_size:], targets[split_size:]

trainset = timeseries_dataset_from_array(X_train, y_train, sequence_length=WINDOW_SIZE,batch_size=1024).prefetch(tf.data.AUTOTUNE)
testset = timeseries_dataset_from_array(X_test, y_test, sequence_length=WINDOW_SIZE,batch_size=1024).prefetch(tf.data.AUTOTUNE)

trainset, testset

(<PrefetchDataset shapes: ((None, None), (None,)), types: (tf.int32, tf.int32)>,
 <PrefetchDataset shapes: ((None, None), (None,)), types: (tf.int32, tf.int32)>)

In [29]:
INPUT_SIZE = WINDOW_SIZE * HORIZON # called "Lookback" in Table 18
THETA_SIZE = INPUT_SIZE + HORIZON

# 1. Setup N-BEATS Block layer
nbeats_block_layer = NBeatsBlock(input_size=INPUT_SIZE,
                                 theta_size=THETA_SIZE,
                                 horizon=HORIZON,
                                 n_neurons=N_NEURONS,
                                 n_layers=N_LAYERS,
                                 name="InitialBlock")

# 2. Create input to stacks
stack_input = layers.Input(shape=(INPUT_SIZE), name="stack_input")

# 3. Create initial backcast and forecast input (backwards predictions are referred to as residuals in the paper)
backcast, forecast = nbeats_block_layer(stack_input)
# Add in subtraction residual link, thank you to: https://github.com/mrdbourke/tensorflow-deep-learning/discussions/174 
residuals = layers.subtract([stack_input, backcast], name=f"subtract_00") 

# 4. Create stacks of blocks
for i, _ in enumerate(range(N_STACKS-1)): # first stack is already creted in (3)

  # 5. Use the NBeatsBlock to calculate the backcast as well as block forecast
  backcast, block_forecast = NBeatsBlock(
      input_size=INPUT_SIZE,
      theta_size=THETA_SIZE,
      horizon=HORIZON,
      n_neurons=N_NEURONS,
      n_layers=N_LAYERS,
      name=f"NBeatsBlock_{i}"
  )(residuals) # pass it in residuals (the backcast)

  # 6. Create the double residual stacking
  residuals = layers.subtract([residuals, backcast], name=f"subtract_{i}") 
  forecast = layers.add([forecast, block_forecast], name=f"add_{i}")

# 7. Put the stack model together
model_nbeats = tf.keras.Model(inputs=stack_input, 
                         outputs=forecast, 
                         name="model_7_N-BEATS")

# 8. Compile with MAE loss and Adam optimizer
model_nbeats.compile(loss="mae",
                optimizer=tf.keras.optimizers.Adam(0.001),
                metrics=["mae", "mse"])

# 9. Fit the model with EarlyStopping and ReduceLROnPlateau callbacks
model_nbeats.fit(trainset,
            epochs=N_EPOCHS,
            validation_data=testset,
            verbose=1,
            callbacks=[tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=200, restore_best_weights=True),
                      tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", patience=100, verbose=1)])

Epoch 1/500
1/1 [==============================] - 8s 8s/step - loss: 4.1110 - mae: 4.1110 - mse: 27.2578 - val_loss: 275.1852 - val_mae: 275.1852 - val_mse: 76139.5391
Epoch 2/500
1/1 [==============================] - 0s 92ms/step - loss: 53.3505 - mae: 53.3505 - mse: 4316.3838 - val_loss: 49.8197 - val_mae: 49.8197 - val_mse: 2484.3989
Epoch 3/500
1/1 [==============================] - 0s 92ms/step - loss: 22.5719 - mae: 22.5719 - mse: 757.2276 - val_loss: 23.7254 - val_mae: 23.7254 - val_mse: 563.0187
Epoch 4/500
1/1 [==============================] - 0s 95ms/step - loss: 8.0478 - mae: 8.0478 - mse: 85.8783 - val_loss: 11.3742 - val_mae: 11.3742 - val_mse: 138.6433
Epoch 5/500
1/1 [==============================] - 0s 95ms/step - loss: 1.5661 - mae: 1.5661 - mse: 4.6962 - val_loss: 30.2953 - val_mae: 30.2953 - val_mse: 931.6605
Epoch 6/500
1/1 [==============================] - 0s 97ms/step - loss: 3.9245 - mae: 3.9245 - mse: 22.3735 - val_loss: 20.6062 - val_mae: 20.6062 - val_mse: 436.1637
Epoch 7/500
1/1 [==============================] - 0s 92ms/step - loss: 2.0749 - mae: 2.0749 - mse: 7.3075 - val_loss: 13.5800 - val_mae: 13.5800 - val_mse: 196.4732
Epoch 8/500
1/1 [==============================] - 0s 92ms/step - loss: 1.3001 - mae: 1.3001 - mse: 2.8038 - val_loss: 8.6164 - val_mae: 8.6164 - val_mse: 86.0643
Epoch 9/500
1/1 [==============================] - 0s 94ms/step - loss: 1.3072 - mae: 1.3072 - mse: 2.9181 - val_loss: 6.0007 - val_mae: 6.0007 - val_mse: 46.5893
Epoch 10/500
1/1 [==============================] - 0s 95ms/step - loss: 1.3768 - mae: 1.3768 - mse: 3.6132 - val_loss: 7.8899 - val_mae: 7.8899 - val_mse: 72.8956
Epoch 11/500
1/1 [==============================] - 0s 92ms/step - loss: 1.1808 - mae: 1.1808 - mse: 2.5116 - val_loss: 10.5027 - val_mae: 10.5027 - val_mse: 121.5299
Epoch 12/500
1/1 [==============================] - 0s 95ms/step - loss: 1.0744 - mae: 1.0744 - mse: 1.8990 - val_loss: 11.9925 - val_mae: 11.9925 - val_mse: 155.4635
Epoch 13/500
1/1 [==============================] - 0s 91ms/step - loss: 1.0880 - mae: 1.0880 - mse: 1.9469 - val_loss: 10.1745 - val_mae: 10.1745 - val_mse: 113.8726
Epoch 14/500
1/1 [==============================] - 0s 92ms/step - loss: 0.9352 - mae: 0.9352 - mse: 1.5327 - val_loss: 7.8895 - val_mae: 7.8895 - val_mse: 72.4789
Epoch 15/500
1/1 [==============================] - 0s 90ms/step - loss: 0.9846 - mae: 0.9846 - mse: 1.8851 - val_loss: 10.0229 - val_mae: 10.0229 - val_mse: 111.1342
Epoch 16/500
1/1 [==============================] - 0s 93ms/step - loss: 0.7920 - mae: 0.7920 - mse: 1.1822 - val_loss: 11.4249 - val_mae: 11.4249 - val_mse: 141.6258
Epoch 17/500
1/1 [==============================] - 0s 92ms/step - loss: 0.8789 - mae: 0.8789 - mse: 1.3791 - val_loss: 9.0592 - val_mae: 9.0592 - val_mse: 92.4096
Epoch 18/500
1/1 [==============================] - 0s 96ms/step - loss: 0.7859 - mae: 0.7859 - mse: 1.1836 - val_loss: 9.1729 - val_mae: 9.1729 - val_mse: 102.4011
Epoch 19/500
1/1 [==============================] - 0s 96ms/step - loss: 0.7631 - mae: 0.7631 - mse: 1.1171 - val_loss: 11.8994 - val_mae: 11.8994 - val_mse: 165.2257
Epoch 20/500
1/1 [==============================] - 0s 198ms/step - loss: 0.7246 - mae: 0.7246 - mse: 0.9961 - val_loss: 11.8724 - val_mae: 11.8724 - val_mse: 167.4798
Epoch 21/500
1/1 [==============================] - 0s 152ms/step - loss: 0.5894 - mae: 0.5894 - mse: 0.7742 - val_loss: 9.3112 - val_mae: 9.3112 - val_mse: 111.5278
Epoch 22/500
1/1 [==============================] - 0s 94ms/step - loss: 0.6951 - mae: 0.6951 - mse: 0.8070 - val_loss: 11.4489 - val_mae: 11.4489 - val_mse: 160.7143
Epoch 23/500
1/1 [==============================] - 0s 90ms/step - loss: 0.5441 - mae: 0.5441 - mse: 0.6714 - val_loss: 11.7398 - val_mae: 11.7398 - val_mse: 183.2197
Epoch 24/500
1/1 [==============================] - 0s 95ms/step - loss: 0.4518 - mae: 0.4518 - mse: 0.4610 - val_loss: 13.0336 - val_mae: 13.0336 - val_mse: 231.3349
Epoch 25/500
1/1 [==============================] - 0s 93ms/step - loss: 0.6069 - mae: 0.6069 - mse: 0.7173 - val_loss: 9.9070 - val_mae: 9.9070 - val_mse: 136.5247
Epoch 26/500
1/1 [==============================] - 0s 93ms/step - loss: 0.5923 - mae: 0.5923 - mse: 0.6518 - val_loss: 11.0149 - val_mae: 11.0149 - val_mse: 141.0626
Epoch 27/500
1/1 [==============================] - 0s 90ms/step - loss: 0.5473 - mae: 0.5473 - mse: 0.6356 - val_loss: 10.1251 - val_mae: 10.1251 - val_mse: 121.2603
Epoch 28/500
1/1 [==============================] - 0s 90ms/step - loss: 0.4764 - mae: 0.4764 - mse: 0.4643 - val_loss: 9.7166 - val_mae: 9.7166 - val_mse: 120.1339
Epoch 29/500
1/1 [==============================] - 0s 91ms/step - loss: 0.4020 - mae: 0.4020 - mse: 0.3361 - val_loss: 11.7492 - val_mae: 11.7492 - val_mse: 171.4209
Epoch 30/500
1/1 [==============================] - 0s 90ms/step - loss: 0.5144 - mae: 0.5144 - mse: 0.5050 - val_loss: 9.6598 - val_mae: 9.6598 - val_mse: 140.0644
Epoch 31/500
1/1 [==============================] - 0s 93ms/step - loss: 0.4885 - mae: 0.4885 - mse: 0.4372 - val_loss: 9.7568 - val_mae: 9.7568 - val_mse: 142.2508
Epoch 32/500
1/1 [==============================] - 0s 92ms/step - loss: 0.4730 - mae: 0.4730 - mse: 0.4748 - val_loss: 11.9626 - val_mae: 11.9626 - val_mse: 188.2372
Epoch 33/500
1/1 [==============================] - 0s 110ms/step - loss: 0.5072 - mae: 0.5072 - mse: 0.5052 - val_loss: 10.9818 - val_mae: 10.9818 - val_mse: 151.5833
Epoch 34/500
1/1 [==============================] - 0s 90ms/step - loss: 0.3429 - mae: 0.3429 - mse: 0.2944 - val_loss: 8.1934 - val_mae: 8.1934 - val_mse: 90.0962
Epoch 35/500
1/1 [==============================] - 0s 90ms/step - loss: 0.5334 - mae: 0.5334 - mse: 0.4835 - val_loss: 10.0698 - val_mae: 10.0698 - val_mse: 113.8772
Epoch 36/500
1/1 [==============================] - 0s 90ms/step - loss: 0.4502 - mae: 0.4502 - mse: 0.4196 - val_loss: 11.8090 - val_mae: 11.8090 - val_mse: 149.7611
Epoch 37/500
1/1 [==============================] - 0s 90ms/step - loss: 0.4767 - mae: 0.4767 - mse: 0.5332 - val_loss: 10.3638 - val_mae: 10.3638 - val_mse: 125.5216
Epoch 38/500
1/1 [==============================] - 0s 93ms/step - loss: 0.3544 - mae: 0.3544 - mse: 0.2936 - val_loss: 10.7202 - val_mae: 10.7202 - val_mse: 141.1552
Epoch 39/500
1/1 [==============================] - 0s 92ms/step - loss: 0.3288 - mae: 0.3288 - mse: 0.2708 - val_loss: 11.8764 - val_mae: 11.8764 - val_mse: 172.5291
Epoch 40/500
1/1 [==============================] - 0s 90ms/step - loss: 0.3867 - mae: 0.3867 - mse: 0.3521 - val_loss: 10.1662 - val_mae: 10.1662 - val_mse: 150.3865
Epoch 41/500
1/1 [==============================] - 0s 90ms/step - loss: 0.3031 - mae: 0.3031 - mse: 0.2450 - val_loss: 10.0479 - val_mae: 10.0479 - val_mse: 140.2458
Epoch 42/500
1/1 [==============================] - 0s 92ms/step - loss: 0.3258 - mae: 0.3258 - mse: 0.3099 - val_loss: 10.1831 - val_mae: 10.1831 - val_mse: 135.4650
Epoch 43/500
1/1 [==============================] - 0s 90ms/step - loss: 0.2441 - mae: 0.2441 - mse: 0.2438 - val_loss: 9.0004 - val_mae: 9.0004 - val_mse: 111.2758
Epoch 44/500
1/1 [==============================] - 0s 93ms/step - loss: 0.3298 - mae: 0.3298 - mse: 0.2489 - val_loss: 10.5292 - val_mae: 10.5292 - val_mse: 133.2399
Epoch 45/500
1/1 [==============================] - 0s 91ms/step - loss: 0.3205 - mae: 0.3205 - mse: 0.2722 - val_loss: 10.5273 - val_mae: 10.5273 - val_mse: 130.8702
Epoch 46/500
1/1 [==============================] - 0s 91ms/step - loss: 0.2942 - mae: 0.2942 - mse: 0.2328 - val_loss: 11.5771 - val_mae: 11.5771 - val_mse: 156.7347
Epoch 47/500
1/1 [==============================] - 0s 91ms/step - loss: 0.2424 - mae: 0.2424 - mse: 0.2129 - val_loss: 11.9764 - val_mae: 11.9764 - val_mse: 170.7700
Epoch 48/500
1/1 [==============================] - 0s 92ms/step - loss: 0.2173 - mae: 0.2173 - mse: 0.2017 - val_loss: 12.5915 - val_mae: 12.5915 - val_mse: 184.7886
Epoch 49/500
1/1 [==============================] - 0s 93ms/step - loss: 0.2275 - mae: 0.2275 - mse: 0.2116 - val_loss: 11.4186 - val_mae: 11.4186 - val_mse: 154.6124
Epoch 50/500
1/1 [==============================] - 0s 92ms/step - loss: 0.2348 - mae: 0.2348 - mse: 0.1737 - val_loss: 12.8594 - val_mae: 12.8594 - val_mse: 180.9010
Epoch 51/500
1/1 [==============================] - 0s 91ms/step - loss: 0.3390 - mae: 0.3390 - mse: 0.2946 - val_loss: 11.3025 - val_mae: 11.3025 - val_mse: 145.7597
Epoch 52/500
1/1 [==============================] - 0s 93ms/step - loss: 0.2114 - mae: 0.2114 - mse: 0.1495 - val_loss: 8.9721 - val_mae: 8.9721 - val_mse: 103.0050
Epoch 53/500
1/1 [==============================] - 0s 92ms/step - loss: 0.3777 - mae: 0.3777 - mse: 0.2926 - val_loss: 10.2666 - val_mae: 10.2666 - val_mse: 124.2589
Epoch 54/500
1/1 [==============================] - 0s 91ms/step - loss: 0.2697 - mae: 0.2697 - mse: 0.1659 - val_loss: 10.7913 - val_mae: 10.7913 - val_mse: 132.2129
Epoch 55/500
1/1 [==============================] - 0s 91ms/step - loss: 0.2924 - mae: 0.2924 - mse: 0.1765 - val_loss: 9.3258 - val_mae: 9.3258 - val_mse: 103.8088
Epoch 56/500
1/1 [==============================] - 0s 93ms/step - loss: 0.2958 - mae: 0.2958 - mse: 0.1757 - val_loss: 10.0384 - val_mae: 10.0384 - val_mse: 124.3317
Epoch 57/500
1/1 [==============================] - 0s 91ms/step - loss: 0.2614 - mae: 0.2614 - mse: 0.1533 - val_loss: 11.9011 - val_mae: 11.9011 - val_mse: 170.2501
Epoch 58/500
1/1 [==============================] - 0s 90ms/step - loss: 0.2327 - mae: 0.2327 - mse: 0.1699 - val_loss: 11.4069 - val_mae: 11.4069 - val_mse: 164.3533
Epoch 59/500
1/1 [==============================] - 0s 90ms/step - loss: 0.2089 - mae: 0.2089 - mse: 0.1191 - val_loss: 11.3776 - val_mae: 11.3776 - val_mse: 155.5713
Epoch 60/500
1/1 [==============================] - 0s 89ms/step - loss: 0.2342 - mae: 0.2342 - mse: 0.1487 - val_loss: 11.5194 - val_mae: 11.5194 - val_mse: 158.0271
Epoch 61/500
1/1 [==============================] - 0s 91ms/step - loss: 0.1981 - mae: 0.1981 - mse: 0.1178 - val_loss: 11.3430 - val_mae: 11.3430 - val_mse: 159.5243
Epoch 62/500
1/1 [==============================] - 0s 91ms/step - loss: 0.1736 - mae: 0.1736 - mse: 0.0921 - val_loss: 11.9200 - val_mae: 11.9200 - val_mse: 168.5190
Epoch 63/500
1/1 [==============================] - 0s 92ms/step - loss: 0.2232 - mae: 0.2232 - mse: 0.1263 - val_loss: 10.4092 - val_mae: 10.4092 - val_mse: 136.8538
Epoch 64/500
1/1 [==============================] - 0s 91ms/step - loss: 0.2581 - mae: 0.2581 - mse: 0.1315 - val_loss: 10.8826 - val_mae: 10.8826 - val_mse: 137.7213
Epoch 65/500
1/1 [==============================] - 0s 91ms/step - loss: 0.1915 - mae: 0.1915 - mse: 0.0945 - val_loss: 11.2033 - val_mae: 11.2033 - val_mse: 141.5624
Epoch 66/500
1/1 [==============================] - 0s 90ms/step - loss: 0.1695 - mae: 0.1695 - mse: 0.0774 - val_loss: 11.7320 - val_mae: 11.7320 - val_mse: 155.0747
Epoch 67/500
1/1 [==============================] - 0s 92ms/step - loss: 0.1477 - mae: 0.1477 - mse: 0.0577 - val_loss: 12.0553 - val_mae: 12.0553 - val_mse: 165.3589
Epoch 68/500
1/1 [==============================] - 0s 90ms/step - loss: 0.1438 - mae: 0.1438 - mse: 0.0514 - val_loss: 13.1994 - val_mae: 13.1994 - val_mse: 189.4563
Epoch 69/500
1/1 [==============================] - 0s 89ms/step - loss: 0.2297 - mae: 0.2297 - mse: 0.1129 - val_loss: 11.0602 - val_mae: 11.0602 - val_mse: 138.6879
Epoch 70/500
1/1 [==============================] - 0s 91ms/step - loss: 0.2102 - mae: 0.2102 - mse: 0.0835 - val_loss: 10.6973 - val_mae: 10.6973 - val_mse: 125.8806
Epoch 71/500
1/1 [==============================] - 0s 93ms/step - loss: 0.2486 - mae: 0.2486 - mse: 0.1140 - val_loss: 13.9060 - val_mae: 13.9060 - val_mse: 197.6577
Epoch 72/500
1/1 [==============================] - 0s 94ms/step - loss: 0.3946 - mae: 0.3946 - mse: 0.2600 - val_loss: 13.0444 - val_mae: 13.0444 - val_mse: 176.3006
Epoch 73/500
1/1 [==============================] - 0s 96ms/step - loss: 0.2768 - mae: 0.2768 - mse: 0.1537 - val_loss: 10.4264 - val_mae: 10.4264 - val_mse: 124.2872
Epoch 74/500
1/1 [==============================] - 0s 94ms/step - loss: 0.3124 - mae: 0.3124 - mse: 0.1662 - val_loss: 10.8932 - val_mae: 10.8932 - val_mse: 138.2229
Epoch 75/500
1/1 [==============================] - 0s 90ms/step - loss: 0.1791 - mae: 0.1791 - mse: 0.0694 - val_loss: 13.4039 - val_mae: 13.4039 - val_mse: 196.6846
Epoch 76/500
1/1 [==============================] - 0s 92ms/step - loss: 0.3705 - mae: 0.3705 - mse: 0.2219 - val_loss: 12.2133 - val_mae: 12.2133 - val_mse: 165.7097
Epoch 77/500
1/1 [==============================] - 0s 92ms/step - loss: 0.2005 - mae: 0.2005 - mse: 0.0912 - val_loss: 10.2715 - val_mae: 10.2715 - val_mse: 115.9604
Epoch 78/500
1/1 [==============================] - 0s 91ms/step - loss: 0.3471 - mae: 0.3471 - mse: 0.1677 - val_loss: 11.8958 - val_mae: 11.8958 - val_mse: 147.4373
Epoch 79/500
1/1 [==============================] - 0s 91ms/step - loss: 0.1762 - mae: 0.1762 - mse: 0.0628 - val_loss: 13.3984 - val_mae: 13.3984 - val_mse: 183.8468
Epoch 80/500
1/1 [==============================] - 0s 96ms/step - loss: 0.2731 - mae: 0.2731 - mse: 0.1317 - val_loss: 11.2952 - val_mae: 11.2952 - val_mse: 134.0453
Epoch 81/500
1/1 [==============================] - 0s 93ms/step - loss: 0.1603 - mae: 0.1603 - mse: 0.0553 - val_loss: 11.4415 - val_mae: 11.4415 - val_mse: 139.9396
Epoch 82/500
1/1 [==============================] - 0s 92ms/step - loss: 0.1406 - mae: 0.1406 - mse: 0.0480 - val_loss: 13.3918 - val_mae: 13.3918 - val_mse: 192.3255
Epoch 83/500
1/1 [==============================] - 0s 89ms/step - loss: 0.2778 - mae: 0.2778 - mse: 0.1337 - val_loss: 12.5169 - val_mae: 12.5169 - val_mse: 177.2485
Epoch 84/500
1/1 [==============================] - 0s 91ms/step - loss: 0.2048 - mae: 0.2048 - mse: 0.0834 - val_loss: 11.3019 - val_mae: 11.3019 - val_mse: 155.0237
Epoch 85/500
1/1 [==============================] - 0s 91ms/step - loss: 0.2755 - mae: 0.2755 - mse: 0.1307 - val_loss: 12.1504 - val_mae: 12.1504 - val_mse: 169.7355
Epoch 86/500
1/1 [==============================] - 0s 91ms/step - loss: 0.1221 - mae: 0.1221 - mse: 0.0394 - val_loss: 12.4824 - val_mae: 12.4824 - val_mse: 169.2410
Epoch 87/500
1/1 [==============================] - 0s 90ms/step - loss: 0.1719 - mae: 0.1719 - mse: 0.0600 - val_loss: 10.4739 - val_mae: 10.4739 - val_mse: 118.1965
Epoch 88/500
1/1 [==============================] - 0s 95ms/step - loss: 0.2161 - mae: 0.2161 - mse: 0.1035 - val_loss: 10.8024 - val_mae: 10.8024 - val_mse: 121.4866
Epoch 89/500
1/1 [==============================] - 0s 95ms/step - loss: 0.1870 - mae: 0.1870 - mse: 0.0826 - val_loss: 12.6186 - val_mae: 12.6186 - val_mse: 163.7833
Epoch 90/500
1/1 [==============================] - 0s 94ms/step - loss: 0.2278 - mae: 0.2278 - mse: 0.0978 - val_loss: 12.3005 - val_mae: 12.3005 - val_mse: 160.5785
Epoch 91/500
1/1 [==============================] - 0s 91ms/step - loss: 0.1514 - mae: 0.1514 - mse: 0.0525 - val_loss: 12.3702 - val_mae: 12.3702 - val_mse: 170.8604
Epoch 92/500
1/1 [==============================] - 0s 92ms/step - loss: 0.1857 - mae: 0.1857 - mse: 0.0678 - val_loss: 14.1363 - val_mae: 14.1363 - val_mse: 222.0586
Epoch 93/500
1/1 [==============================] - 0s 95ms/step - loss: 0.2218 - mae: 0.2218 - mse: 0.0911 - val_loss: 13.1474 - val_mae: 13.1474 - val_mse: 206.7191
Epoch 94/500
1/1 [==============================] - 0s 91ms/step - loss: 0.1819 - mae: 0.1819 - mse: 0.0792 - val_loss: 12.3073 - val_mae: 12.3073 - val_mse: 186.6662
Epoch 95/500
1/1 [==============================] - 0s 94ms/step - loss: 0.1783 - mae: 0.1783 - mse: 0.0706 - val_loss: 12.6521 - val_mae: 12.6521 - val_mse: 187.1981
Epoch 96/500
1/1 [==============================] - 0s 92ms/step - loss: 0.1266 - mae: 0.1266 - mse: 0.0406 - val_loss: 11.5189 - val_mae: 11.5189 - val_mse: 156.2711
Epoch 97/500
1/1 [==============================] - 0s 96ms/step - loss: 0.1341 - mae: 0.1341 - mse: 0.0422 - val_loss: 12.1073 - val_mae: 12.1073 - val_mse: 166.1419
Epoch 98/500
1/1 [==============================] - 0s 94ms/step - loss: 0.1348 - mae: 0.1348 - mse: 0.0439 - val_loss: 12.2581 - val_mae: 12.2581 - val_mse: 168.3834
Epoch 99/500
1/1 [==============================] - 0s 92ms/step - loss: 0.1305 - mae: 0.1305 - mse: 0.0437 - val_loss: 11.4148 - val_mae: 11.4148 - val_mse: 151.1778
Epoch 100/500
1/1 [==============================] - 0s 89ms/step - loss: 0.1923 - mae: 0.1923 - mse: 0.0679 - val_loss: 12.7998 - val_mae: 12.7998 - val_mse: 179.8281
Epoch 101/500
1/1 [==============================] - 0s 92ms/step - loss: 0.1741 - mae: 0.1741 - mse: 0.0623 - val_loss: 12.0962 - val_mae: 12.0962 - val_mse: 161.6638
Epoch 102/500
1/1 [==============================] - 0s 91ms/step - loss: 0.1255 - mae: 0.1255 - mse: 0.0420 - val_loss: 10.6599 - val_mae: 10.6599 - val_mse: 133.7345
Epoch 103/500
1/1 [==============================] - 0s 91ms/step - loss: 0.2540 - mae: 0.2540 - mse: 0.1057 - val_loss: 12.0554 - val_mae: 12.0554 - val_mse: 163.5223
Epoch 104/500
1/1 [==============================] - 0s 91ms/step - loss: 0.1280 - mae: 0.1280 - mse: 0.0409 - val_loss: 13.7645 - val_mae: 13.7645 - val_mse: 203.4055
Epoch 105/500
1/1 [==============================] - 0s 153ms/step - loss: 0.2872 - mae: 0.2872 - mse: 0.1373 - val_loss: 12.9010 - val_mae: 12.9010 - val_mse: 179.3242
Epoch 106/500
1/1 [==============================] - 0s 151ms/step - loss: 0.1554 - mae: 0.1554 - mse: 0.0580 - val_loss: 11.8047 - val_mae: 11.8047 - val_mse: 151.9479
Epoch 107/500
1/1 [==============================] - 0s 122ms/step - loss: 0.2222 - mae: 0.2222 - mse: 0.0725 - val_loss: 12.6973 - val_mae: 12.6973 - val_mse: 174.1688
Epoch 108/500
1/1 [==============================] - 0s 92ms/step - loss: 0.1240 - mae: 0.1240 - mse: 0.0382 - val_loss: 13.1957 - val_mae: 13.1957 - val_mse: 187.0402
Epoch 109/500
1/1 [==============================] - 0s 93ms/step - loss: 0.1690 - mae: 0.1690 - mse: 0.0609 - val_loss: 12.1434 - val_mae: 12.1434 - val_mse: 160.2193

Epoch 00109: ReduceLROnPlateau reducing learning rate to 0.00010000000474974513.
Epoch 110/500
1/1 [==============================] - 0s 103ms/step - loss: 0.1432 - mae: 0.1432 - mse: 0.0504 - val_loss: 12.1481 - val_mae: 12.1481 - val_mse: 160.0187
Epoch 111/500
1/1 [==============================] - 0s 99ms/step - loss: 0.1390 - mae: 0.1390 - mse: 0.0485 - val_loss: 12.2702 - val_mae: 12.2702 - val_mse: 162.4735
Epoch 112/500
1/1 [==============================] - 0s 91ms/step - loss: 0.1229 - mae: 0.1229 - mse: 0.0423 - val_loss: 12.4839 - val_mae: 12.4839 - val_mse: 167.0820
Epoch 113/500
1/1 [==============================] - 0s 91ms/step - loss: 0.1082 - mae: 0.1082 - mse: 0.0362 - val_loss: 12.7021 - val_mae: 12.7021 - val_mse: 171.9244
Epoch 114/500
1/1 [==============================] - 0s 89ms/step - loss: 0.0976 - mae: 0.0976 - mse: 0.0338 - val_loss: 12.8336 - val_mae: 12.8336 - val_mse: 174.7676
Epoch 115/500
1/1 [==============================] - 0s 89ms/step - loss: 0.0937 - mae: 0.0937 - mse: 0.0329 - val_loss: 12.8587 - val_mae: 12.8587 - val_mse: 175.0728
Epoch 116/500
1/1 [==============================] - 0s 92ms/step - loss: 0.0865 - mae: 0.0865 - mse: 0.0307 - val_loss: 12.7817 - val_mae: 12.7817 - val_mse: 173.1081
Epoch 117/500
1/1 [==============================] - 0s 90ms/step - loss: 0.0720 - mae: 0.0720 - mse: 0.0265 - val_loss: 12.6413 - val_mae: 12.6413 - val_mse: 169.8415
Epoch 118/500
1/1 [==============================] - 0s 90ms/step - loss: 0.0688 - mae: 0.0688 - mse: 0.0237 - val_loss: 12.5883 - val_mae: 12.5883 - val_mse: 168.8627
Epoch 119/500
1/1 [==============================] - 0s 91ms/step - loss: 0.0708 - mae: 0.0708 - mse: 0.0231 - val_loss: 12.6680 - val_mae: 12.6680 - val_mse: 171.0886
Epoch 120/500

In [30]:
model_nbeats.predict(tf.expand_dims(k9_list[-WINDOW_SIZE:],axis=0))

array([[26.017815]], dtype=float32)

Based on the same prediction model, there would be **26 K9 deaths** in the next year 2023 provided all the contributing factors continue to influence in the same way. Most of the dogs would like be passed due to **gunfire** and the most risk is involved in **California** and **Florida.**

### Thank you for going through my notebook. Please leave a comment about what can be done better for this notebook.